### ISSUE TITLE
Pathmuncher not showing up for players

### ISSUE THREAD

**Issue by RevenantBob** [MrPrimate/pathmuncher#48]
**Describe the bug**
Pathmuncher option is only showing for GM. Players are owners of sheets, and Trusted Players. No option available on sheet.

**To Reproduce**
1. Open Sheet as Trusted Player
2. No Pathmuncher Option

**Expected behavior**
Pathmuncher should be available for players.

**Screenshots**

**Environment:**
 - Browser Edge
 - Foundry Version 12 stable 327
 - Pathfinder System Version 6.0.4
 - Module Version 1.3.0
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
 - Details of any errors in the browser console (press F12).

**Comment by MrPrimate** [comment]
Pathmuncher currently requires the create actor permission, due to how it works out what choices have been taken, so your players will need this permission i think

**Comment by depressobbq** [comment]
confirming, on the newest build of V12 the pathmuncher option is no longer at the top of the character sheet. the module is loaded trhe permissions are all set and the options gone, even for the GM account there is no longer an option at the top of the character sheet to import via pathmuncher.

**Comment by wyaruss** [comment]
I think this is solved--my players were able to see the link as of our session a couple weeks ago.

**Comment by csheepy** [comment]
Still a problem for me. My players can't see the pathmuncher button.
